version: '3.0'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rec
      POSTGRES_PASSWORD: rec*1212
      PG: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - 5432:5432

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: rec
      MONGO_INITDB_ROOT_PASSWORD: rec*1212
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  node-red:
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - ./node-red-data:/data

